export const USER_REGISTER_REQUEST = 'USER-REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER-REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER-REGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER-SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER-SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER-SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER-SIGNOUT';